#storing varaible in seperate file
- name: variables from files
  hosts: localhost
  vars_files:
  - variable.yaml
  tasks:
  - name: printing the variables
    ansible.builtin.debug:
     msg: "iam learning {{NAME}}, duration is {{DURATION}}"